### ISSUE TITLE
Theme Development

### ISSUE THREAD

**Issue by kacperbondaruk** [kacperbondaruk/VSC-Theme_1.0.1-Alpha-Milkyway#1]
#TODO
- [ ]  Improve elements that still are using default theme color scheme.
- [ ]  Add more refined examples in Readme
- [ ]  Add Comments in settings.json with change description
